### ISSUE TITLE
Use helm-chart for metrics server

### ISSUE THREAD

**Issue by tuxpeople** [tuxpeople/k8s-homelab#209]
Switch to the helm-chart for metrics server. Its going to be released soon:

https://github.com/kubernetes-sigs/metrics-server/pull/670

**Comment by onedr0p** [comment]
Feel free to prepare for it

https://github.com/onedr0p/home-cluster/commit/d76b9d7916801ebd9b77dc9742f1801f3d809b96

**Comment by tuxpeople** [comment]
@onedr0p that's a great idea. I'm also ready now :-) thanks!

https://github.com/tuxpeople/k8s-homelab/tree/tuxpeople/issue209
