### ISSUE TITLE
Switch mystrom exporter image

### ISSUE THREAD

**Issue by peschmae** [tuxpeople/k8s-homelab#365]
Due to the changes to docker hub, new container images for the mystrom-exporter are now published only on github.

They are automatically built cross-platform using github actions, and you should update your reference to `ghcr.io/peschmae/exporter-go-mystrom:latest` as seen on https://github.com/peschmae/exporter-go-mystrom/pkgs/container/exporter-go-mystrom

The new image now also contains better logging, on startup and on failure

**Comment by tuxpeople** [comment]
Thanks, I highly appreciate letting me know, and also appreciating the fact its cross platform. So I don‘t need to rebuild it myself once I go back to ARM.
